repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --config=pyproject.toml
        language: system
        types: [python]
        files: ^custom_components/
        # Optionnel : décommenter pour ne pas bloquer le commit
        # stages: [manual]
        
      - id: black
        name: black
        entry: black --check --config=pyproject.toml
        language: system
        types: [python]
        files: ^custom_components/
        # Optionnel : décommenter pour ne pas bloquer le commit
        # stages: [manual]
        
      - id: isort
        name: isort
        entry: isort --check-only --settings-path=pyproject.toml
        language: system
        types: [python]
        files: ^custom_components/
        # Optionnel : décommenter pour ne pas bloquer le commit
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
